name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest ./backend

      - name: Push Docker image to Docker Hub
        run: | 
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/Dockerization-Nodejs-App
          git pull origin master
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          docker-compose down
          docker-compose up -d
            EOF